### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by aa563011992** [AlekseiBazhenov/CanBusApp#1]
![QQ截图20201231170345](https://user-images.githubusercontent.com/16330466/103403173-3b749c00-4b8a-11eb-8e32-4218133cf1b7.png)

**Comment by aa563011992** [comment]
2020-12-31 17:09:35.493 3240-3240/ru.test.testjni W/ru.test.testjni: type=1400 audit(0.0:1258585): avc: denied { create } for pid=3240 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:r:untrusted_app_27:s0:c512,c768 tclass=can_socket permissive=0
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err: java.io.IOException: Permission denied
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at ru.test.testjni.CanSocket._openSocketRAW(Native Method)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at ru.test.testjni.CanSocket.<init>(CanSocket.java:347)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at ru.test.testjni.canbus.CanUtils.initCan0(CanUtils.java:14)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at ru.test.testjni.service.CanService.onStartCommand(CanService.java:78)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4776)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at android.app.ActivityThread.access$3100(ActivityThread.java:308)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2346)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at android.os.Looper.loop(Looper.java:219)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8347)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
2020-12-31 17:09:35.498 3240-3240/ru.test.testjni W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
2020-12-31 17:09:35.499 3240-3291/ru.test.testjni D/OpenGLRenderer: disableOutlineDraw is true
2020-12-31 17:09:35.500 3240-3309/ru.test.testjni I/QarthLog: [PatchStore] createDisableExceptionQarthFile
2020-12-31 17:09:35.500 3240-3309/ru.test.testjni I/QarthLog: [PatchStore] create disable file for ru.test.testjni uid is 10585
2020-12-31 17:09:35.500 3240-3309/ru.test.testjni E/AndroidRuntime: FATAL EXCEPTION: Thread-2
    Process: ru.test.testjni, PID: 3240
    java.lang.NullPointerException: Attempt to invoke virtual method 'ru.test.testjni.CanSocket$CanFrame ru.test.testjni.CanSocket.recv()' on a null object reference
        at ru.test.testjni.canbus.CanUtils.revCan0Data(CanUtils.java:20)
        at ru.test.testjni.service.CanService.startCanBusListening(CanService.java:91)
        at ru.test.testjni.service.CanService.access$000(CanService.java:33)
        at ru.test.testjni.service.CanService$1.run(CanService.java:56)
        at java.lang.Thread.run(Thread.java:929)

**Comment by AlekseiBazhenov** [comment]
@aa563011992 It seems you have another CAN interface name. Try to change from "can0" to your interface name in CanUtils.initCan0(). Also you may try to use another CanSocket.Mode parameter

**Comment by aa563011992** [comment]
I see.Thank you very much!
